version: "2.1"

networks:
  dockprom-loki_monitor-net:
    external: true

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    volumes:
      - ./loki-opt:/opt/loki
    expose:
      - 3100
    #command: -config.file=/etc/loki/local-config.yaml
    command: -config.file=/opt/loki/loki-config.yaml
    networks:
      - dockprom-loki_monitor-net
    labels:
      org.label-schema.group: "monitoring"


  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail-opt:/opt/promtail
      - /var/log:/var/log
    #command: -config.file=/etc/promtail/config.yml
    command: -config.file=/opt/promtail/promtail-config.yml
    networks:
      - dockprom-loki_monitor-net
    labels:
      org.label-schema.group: "monitoring"


#  grafana:
#    environment:
#      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        mkdir -p /etc/grafana/provisioning/datasources
#        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
#        apiVersion: 1
#        datasources:
#        - name: Loki
#          type: loki
#          access: proxy
#          orgId: 1
#          url: http://loki:3100
#          basicAuth: false
#          isDefault: true
#          version: 1
#          editable: false
#        EOF
#        /run.sh
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    networks:
#      - loki
